/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainframe;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author said.said
 */
public class Panel extends javax.swing.JPanel {

    int kantal, kx, ky;
    int hb;
    int x, y, bredd, höjd;
    Color färg;
    int poäng = 0;
    int antal = 0;

    int be = 50;

    ArrayList<Cirkel> cirklar = new ArrayList<>();
    Sikte s = new Sikte(200, 100, 30);
    Cirkel c = new Cirkel(x, y, bredd, höjd, färg);

    public Panel() {
        initComponents();
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Random r = new Random();
        int bredd = r.nextInt(80) + 20;
        int höjd = r.nextInt(80) + 20;

        txalista.setText("");

        x = (int) (Math.random() * 400);
        y = (int) (Math.random() * 400);

        for (int i = 0; i < cirklar.size(); i++) {
            cirklar.get(i).rita(g);
        }
        txalista.append(poäng + "\n");
        s.rita(g);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txalista = new javax.swing.JTextArea();
        btnlägg = new javax.swing.JButton();

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        txalista.setColumns(20);
        txalista.setRows(5);
        jScrollPane1.setViewportView(txalista);

        btnlägg.setText("Lägg till kvadrat");
        btnlägg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnläggActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(btnlägg)
                .addGap(180, 180, 180)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlägg)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        s.x = evt.getX();
        s.y = evt.getY();
        repaint();

    }//GEN-LAST:event_formMouseMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Random r = new Random();
        int bredd = r.nextInt(80) + 20;
        int höjd = r.nextInt(80) + 20;
        Color färg = new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        //cirklar.add(new Cirkel(evt.getX(), evt.getY(), 20, 20, Color.GRAY));

        for (int i = 0; i < antal; i++) {
            if (evt.getX() >= cirklar.get(i).x - be && evt.getX() <= cirklar.get(i).x + be && evt.getY() >= cirklar.get(i).y - be && evt.getY() <= cirklar.get(i).y + be) {
                cirklar.remove(i);
                poäng++;
                antal--;
            }
        }

        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void btnläggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnläggActionPerformed
        antal++;
        cirklar.add(new Cirkel(x, y, be, be, Color.red));
        repaint();
    }//GEN-LAST:event_btnläggActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlägg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txalista;
    // End of variables declaration//GEN-END:variables
}
